services:
  db:
    image: postgres:15
    container_name: premarketprice-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: premarketprice
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  premarketprice:
    build: .
    container_name: premarketprice-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POLYGON_API_KEY=${POLYGON_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/premarketprice
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data: 